# Generated by Django 4.2.3 on 2023-12-22 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default=None, null=True, upload_to='')),
                ('description', models.TextField(default=None, max_length=200, null=True)),
                ('rates', models.IntegerField(default=None, null=True)),
                ('idols', models.CharField(default=None, max_length=1000, null=True)),
                ('fans', models.CharField(default=None, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
