# Generated by Django 4.2.3 on 2023-12-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fans',
            field=models.CharField(default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idols',
            field=models.CharField(default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rates',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
