# Generated by Django 4.2.3 on 2023-12-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0004_alter_profile_fans_alter_profile_idols_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to='profilePictures/'),
        ),
    ]
