# Generated by Django 4.2.3 on 2023-12-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0006_alter_post_movie_where_to_watch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fans',
            field=models.CharField(blank=True, default=0, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idols',
            field=models.CharField(blank=True, default=0, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profilePictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
