# Generated by Django 4.2.3 on 2023-12-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0007_alter_post_rate_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends_haven_app.category'),
        ),
    ]
