# Generated by Django 4.2.3 on 2023-12-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0009_alter_post_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artist',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
