# Generated by Django 4.2.3 on 2023-12-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0010_post_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
