# Generated by Django 4.2.3 on 2023-12-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0011_remove_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
