# Generated by Django 4.2.3 on 2023-12-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0014_category_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Movie_where_to_watch',
        ),
        migrations.RemoveField(
            model_name='post',
            name='TV_where_to_watch',
        ),
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='post',
            name='instructions',
        ),
        migrations.AddField(
            model_name='post',
            name='answers',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sections',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
