# Generated by Django 4.2.3 on 2023-12-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_haven_app', '0015_remove_post_movie_where_to_watch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fanNum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idolNum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
